apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo02b
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: /demo02b
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo02b
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: manual
---
apiVersion: v1
kind: Pod
metadata:
  name: demo02b
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - mountPath: /demo02b
      name: demo02b
  volumes:
  - name: demo02b
    persistentVolumeClaim:
      claimName: demo02b