apiVersion: v1
kind: Pod
metadata:
  name: demo07a
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources: 
      requests:
        cpu: 500m
        memory: 1000Mi
      limits:
        cpu: 1000m
        memory: 2000Mi