apiVersion: v1
kind: Pod
metadata:
  name: demo08b
spec:
  containers:
  - name: nginx
    image: nginx:latest
  tolerations:
  - key: skynet
    operator: Equal
    value: "true"
    effect: NoSchedule