apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: demo10
spec:
  selector:
    matchLabels:
      app: demo10
  template:
    metadata:
      labels:
        app: demo10
    spec:
      containers:
        - name: fluentbit
          image: "cr.fluentbit.io/fluent/fluent-bit:2.0.5"
