apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo06
spec:
  selector:
    matchLabels:
      purpose: demo06
  replicas: 3
  template: 
    metadata:
      labels:
        purpose: demo06
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
          - containerPort: 80